### ISSUE TITLE
Generator: component path option required

### ISSUE THREAD

**Issue by goulinkh** [canonical/pragma#83]
When running: `yo @canonical/canonical-ds`, the generator errors with the following message:
```console
✖️ An error occured while running @canonical/canonical-ds:app#prompting
Error  

Did not provide required argument componentPath!
```

`componentPath` shouldn't be required, and have a default value.

**Comment by goulinkh** [comment]
Additionally, when provide a `componentPath`, example `src/ui` it creates files in the root of the folder: `ui/ui.tsx`, `ui/types.ts`,...

**Comment by jmuzina** [comment]
Thanks for the report, @goulinkh ! I've filed a PR to fix the first issue about the default path.

As for your second issue, I'm not sure I understand the problem. What would you expect the file structure to be after running `yo @canonical/canonical-ds MyComponent`? Are you expecting an intermediate folder?

Currently this is what is generated:
```
MyComponent
├── MyComponent.test.tsx
├── MyComponent.tsx
├── index.ts
└── types.ts
```

Are you expecting this?
```
MyComponent
└── MyComponent
    ├── MyComponent.test.tsx
    ├── MyComponent.tsx
    ├── index.ts
    └── types.ts
```
